version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: atlas_dev
      POSTGRES_USER: atlas
      POSTGRES_PASSWORD: atlas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  atlas-services:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile.dev
    ports:
      - "8080:8080"    # Main application
      - "50051:50051"  # gRPC services
    depends_on:
      - postgres
      - redis
    volumes:
      - ../..:/workspace
    environment:
      - DATABASE_URL=postgresql://atlas:atlas@postgres:5432/atlas_dev
      - REDIS_URL=redis://redis:6379

volumes:
  postgres_data:
  redis_data:
