version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alphine
    container_name: atlas-postgres
    environment:
      POSTGRES_DB: atlas_dev
      POSTGRES_USER: atlas
      POSTGRES_PASSWORD: atlas
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./deploy/sql/init-db.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U atlas -d atlas_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - atlas_network
    restart: unless-stopped

  # Redis Cache/Message Broker
  redis:
    image: redis:7-alphine
    container_name: atlas-redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - atlas-network
    restart: unless-stopped
 
  #ATLAS Development Environment
  atlas-dev:
    image: ghcr.io/csufresno-unmannedsystemsresearchteam/atlas-dev:latest 
    container_name: atlas-dev
    working_dir: /workspace
    environment:
      # Database connections
      - DATABASE_URL=postgresql://atlas:atlas@postgres:5432/atlas_dev
      - REDIS_URL=redis://redis:6379
      
      # ATLAS configuration
      - ATLAS_ENV=development
      - ATLAS_LOG_LEVEL=DEBUG

      # Development settings
      - VCPKG_ROOT=/opt/vcpkg
      - CMAKE_BUILD_TYPE=Debug
      - CMAKE_EXPORT_COMPILE_COMMANDS=ON
    ports:
      # Main application ports
      - "8080:8080" # ATLAS UI
      - "8081:8081" # API Gateway

      # gRPC service ports
      - "50051:50051" # Protocol Service
      - "50052:50052" # Mission Service
      - "50053:50053" # Geofencing Service
      - "50054:50054" # Telemetry Service
      - "50055:50055" # Alert Service
      - "50056:50056" # Radio Service
      
      # Development tools
      - "9229:9229" # Node.js debugger (if needed)
      - "5678:5678" # Python debugger
    volumes:
      # Mount souce code (local repository)
      - .:/workspace

      # Persistent build cache
      - atlas_build_cache:/workspace/build

      # Persistent vcpkg packages
      - atlas_vcpkg_cache:/opt/vcpkg/installed

      # Git configuration (optional, for commits inside container)
      - ~/.gitconfig:/home/atlas/.gitconfig:ro
      - ~/.ssh:/home/atlas/.ssh:ro
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - atlas-network

    # Keep container running for development
    tty: true
    stdin_open: true
    restart: unless-stopped

    # Use atlas user (non-root)
    user: atlas

# Named volumes for persistent data
volumes:
  # Database data (survives container restarts)
  postgres_data:
    name: atlas_postgres_data
   
  # Database data (survives container restarts)
  redis_data:
    name: atlas_redis_data

  # Build cache
  atlas_build_cache:
    name: atlas_build_cache

  # vcpkg packages cache
  atlas_vcpkg_cache:
    name: atlas_vcpkg_cache

# Custom network for service communication
networks:
  atlas-network:
    name: atlas-development
    driver: bridge
