name: Dependency Updates

on:
  schedule:
    - cron: '0 6 * * 1'  # Weekly on Monday
  workflow_dispatch:

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Update vcpkg baseline
      run: |
        cd vcpkg
        git fetch origin
        LATEST_COMMIT=$(git rev-parse origin/master)
        cd ..
        sed -i "s/\"builtin-baseline\": \".*\"/\"builtin-baseline\": \"$LATEST_COMMIT\"/" vcpkg.json
    
    - name: Test with updated dependencies
      run: |
        cmake -B build -S . -G Ninja
        cmake --build build
        cd build && ctest --output-on-failure
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update vcpkg baseline'
        title: 'Automated Dependency Update'
        body: |
          Automated update of vcpkg baseline to latest version.
          
          - Updated vcpkg baseline
          - All tests pass with new dependencies
          
          Please review and merge if appropriate.
        branch: automated/dependency-update
        delete-branch: true
